name: Mi Primer Workflow

on:
  push:
    branches:
      - main

jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "se hizo un push a la rama main"
